use serde::Serialize;

#[derive(Clone, Copy, Debug, Serialize)]
pub struct SwitchMeta {
    pub name: &'static str,
    pub display: &'static str,
    pub brand: &'static str,
    #[serde(rename = "type")]
    pub kind: &'static str,
    pub color: &'static str,
    pub contributor: &'static str,
    pub norm: f32,
}

pub const CATALOG: &[SwitchMeta] = &[
    meta(
        "aflion-carrot",
        "Carrot Orange",
        "Aflion",
        "Tactile · 37g",
        "#ED802E",
        "",
        0.96,
    ),
    meta(
        "akko-piano-pro",
        "Piano Pro",
        "Akko",
        "Linear · 45g",
        "#9E73C7",
        "Alice (@aliceinnny)",
        3.0,
    ),
    meta(
        "akko-cs-jelly-black",
        "CS Jelly Black",
        "Akko",
        "Linear · 50g",
        "#292930",
        "",
        3.5,
    ),
    meta(
        "akko-v3-pro-cream-yellow",
        "V3 Cream Yellow Pro",
        "Akko",
        "Linear · 50g",
        "#F5DB80",
        "",
        3.5,
    ),
    meta(
        "akko-clicky-pink",
        "Clicky Pink",
        "Akko",
        "Clicky · 50g",
        "#ED739E",
        "",
        0.9,
    ),
    meta(
        "lofree-flow-2-surfer",
        "Surfer",
        "Lofree",
        "Low-profile linear · 40g",
        "#FFFFFF",
        "",
        3.5,
    ),
    meta(
        "lofree-flow-2-void",
        "Void",
        "Lofree",
        "Low-profile silent · 40g",
        "#CCCCD1",
        "",
        3.5,
    ),
    meta(
        "lofree-flow-2-pulse",
        "Pulse",
        "Lofree",
        "Low-profile tactile · 40g",
        "#42424A",
        "",
        3.5,
    ),
    meta(
        "alps-skcm-blue",
        "SKCM Blue",
        "Alps",
        "Clicky · 70g",
        "#4D80CC",
        "",
        0.85,
    ),
    meta(
        "drop-holy-panda",
        "Holy Panda",
        "Drop",
        "Tactile · 67g",
        "#D98C33",
        "",
        0.9,
    ),
    meta(
        "durock-alpaca",
        "Alpaca",
        "Durock",
        "Linear · 62g",
        "#E6CCB3",
        "",
        1.0,
    ),
    meta(
        "gateron-ink-black",
        "Ink Black",
        "Gateron",
        "Linear · 60g",
        "#333340",
        "",
        1.0,
    ),
    meta(
        "gateron-ink-red",
        "Ink Red",
        "Gateron",
        "Linear · 45g",
        "#C74747",
        "",
        1.0,
    ),
    meta(
        "gateron-turquoise-tealios",
        "Turquoise Tealios",
        "Gateron",
        "Linear · 63.5g",
        "#40BFB3",
        "",
        1.0,
    ),
    meta(
        "ibm-buckling-spring",
        "Buckling Spring",
        "IBM",
        "Clicky · 65g",
        "#B3B3A6",
        "",
        0.7,
    ),
    meta(
        "kailh-box-navy",
        "Box Navy",
        "Kailh",
        "Clicky · 75g",
        "#26408C",
        "",
        0.8,
    ),
    meta(
        "iqunix-mq80",
        "MQ80",
        "IQUNIX",
        "Low-profile linear · 40g",
        "#4DA6D9",
        "Alex (@aliszu)",
        0.75,
    ),
    meta(
        "keychron-k2-max-red",
        "Gateron Red",
        "Keychron",
        "Linear · 45g",
        "#C74747",
        "",
        0.55,
    ),
    meta(
        "keychron-k2-max-brown",
        "Gateron Brown",
        "Keychron",
        "Tactile · 55g",
        "#8C7047",
        "Himanshu (@himanhacks)",
        0.85,
    ),
    meta(
        "lizard",
        "Lizard",
        "Quirky",
        "Gecko · lol",
        "#73BF4D",
        "",
        1.0,
    ),
    meta(
        "novelkeys-cream",
        "Cream",
        "NovelKeys",
        "Linear · 55g",
        "#F2E6CC",
        "",
        1.0,
    ),
    meta(
        "topre-classic",
        "Classic",
        "Topre",
        "Tactile · 45g",
        "#998CA6",
        "",
        1.0,
    ),
];

const fn meta(
    name: &'static str,
    display: &'static str,
    brand: &'static str,
    kind: &'static str,
    color: &'static str,
    contributor: &'static str,
    norm: f32,
) -> SwitchMeta {
    SwitchMeta {
        name,
        display,
        brand,
        kind,
        color,
        contributor,
        norm,
    }
}

#[must_use]
pub fn find(name: &str) -> Option<SwitchMeta> {
    CATALOG.iter().copied().find(|item| item.name == name)
}
