/* auto-generated from tools/ui.html — do not edit */

const char UI_HTML[] =
"<!doctype html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<title>keebyd — switch picker</title>\n"
"<style>\n"
":root{--bg:#0e0e10;--panel:#17171a;--panel2:#1e1e22;--line:#2a2a30;--fg:#ececf0;--dim:#9a9aa3;--accent:#9E73C7}\n"
"*{box-sizing:border-box;margin:0;padding:0}\n"
"body{background:var(--bg);color:var(--fg);font:14px/1.45 system-ui,-apple-system,sans-serif;padding:24px;max-width:1100px;margin:0 auto}\n"
"header{display:flex;align-items:center;gap:14px;margin-bottom:20px}\n"
"h1{font-size:20px;font-weight:700;letter-spacing:-.5px}\n"
".badge{font-size:11px;color:var(--dim);border:1px solid var(--line);border-radius:999px;padding:2px 10px}\n"
".spacer{flex:1}\n"
"button{cursor:pointer;border:1px solid var(--line);background:var(--panel2);color:var(--fg);border-radius:10px;padding:8px 14px;font-size:13px;transition:background .15s}\n"
"button:hover{background:#2a2a30}\n"
"button.primary{background:var(--accent);border-color:transparent;color:#fff;font-weight:600}\n"
"section{margin-bottom:26px}\n"
"h2{font-size:13px;text-transform:uppercase;letter-spacing:1.2px;color:var(--dim);margin-bottom:10px}\n"
".grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:10px}\n"
".brand{margin-bottom:16px}\n"
".brand h3{font-size:12px;color:var(--dim);margin-bottom:8px;font-weight:600}\n"
".card{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:12px 14px;cursor:pointer;position:relative;transition:border-color .15s,transform .05s}\n"
".card:hover{border-color:#3d3d46}\n"
".card.active{border-color:var(--accent);box-shadow:0 0 0 1px var(--accent)}\n"
".card:active{transform:scale(.98)}\n"
".card .row{display:flex;align-items:center;gap:8px}\n"
".dot{width:14px;height:14px;border-radius:50%;flex:none;border:1px solid rgba(255,255,255,.2)}\n"
".name{font-weight:600;font-size:13.5px}\n"
".meta{font-size:11.5px;color:var(--dim);margin-top:3px}\n"
".by{font-size:10.5px;color:#77777f;margin-top:2px;font-style:italic}\n"
".star{position:absolute;top:8px;right:10px;background:none;border:none;color:#55555e;font-size:15px;padding:2px}\n"
".star.on{color:#f5c542}\n"
".toggle{display:flex;align-items:center;justify-content:space-between;background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:10px 14px;margin-bottom:8px}\n"
".toggle label{font-size:13px}\n"
".sw{width:38px;height:22px;background:#33333b;border-radius:999px;position:relative;transition:background .15s;flex:none}\n"
".sw:after{content:\"\";position:absolute;top:3px;left:3px;width:16px;height:16px;border-radius:50%;background:#fff;transition:left .15s}\n"
".sw.on{background:var(--accent)}\n"
".sw.on:after{left:19px}\n"
".slider-row{display:flex;align-items:center;gap:12px;background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:10px 14px;margin-bottom:8px}\n"
".slider-row label{font-size:13px;width:150px;flex:none}\n"
".slider-row input[type=range]{flex:1;accent-color:var(--accent)}\n"
".val{font-size:12px;color:var(--dim);width:42px;text-align:right;font-variant-numeric:tabular-nums}\n"
".pad{background:var(--panel);border:1px solid var(--line);border-radius:14px;height:170px;position:relative;cursor:crosshair;overflow:hidden}\n"
".pad .dotp{position:absolute;width:18px;height:18px;border-radius:50%;background:var(--accent);transform:translate(-50%,-50%);pointer-events:none;box-shadow:0 0 12px var(--accent)}\n"
".pad .x,.pad .y{position:absolute;background:rgba(255,255,255,.06)}\n"
".pad .x{left:0;right:0;height:1px}\n"
".pad .y{top:0;bottom:0;width:1px}\n"
".pad-labels{display:flex;justify-content:space-between;font-size:11px;color:var(--dim);margin-top:6px}\n"
"#keys{display:grid;grid-template-columns:repeat(15,1fr);gap:3px;background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:10px}\n"
".key{height:26px;background:var(--panel2);border-radius:5px;font-size:8.5px;display:flex;align-items:center;justify-content:center;color:var(--dim);transition:background .1s,color .1s}\n"
".key.lit{background:var(--accent);color:#fff}\n"
".w15{grid-column:span 15}.w2{grid-column:span 2}.w125{grid-column:span 1.5}\n"
"select{background:var(--panel2);color:var(--fg);border:1px solid var(--line);border-radius:8px;padding:6px 10px;font-size:13px}\n"
".hint{font-size:11px;color:var(--dim);margin-top:4px}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"  <h1>keebyd</h1><span class=\"badge\" id=\"cur\">—</span><span class=\"badge\" id=\"engine\">—</span>\n"
"  <div class=\"spacer\"></div>\n"
"  <button id=\"muteBtn\">Mute</button>\n"
"</header>\n"
"\n"
"<section>\n"
"  <h2>Switches <span style=\"text-transform:none;letter-spacing:0\">— hover to preview, click to choose</span></h2>\n"
"  <div id=\"switches\"></div>\n"
"</section>\n"
"\n"
"<section>\n"
"  <h2>Tone pad <span style=\"text-transform:none;letter-spacing:0\">— drag: left = softer, right = brighter; up = lower pitch, down = higher</span></h2>\n"
"  <div class=\"pad\" id=\"pad\"><div class=\"x\"></div><div class=\"y\"></div><div class=\"dotp\" id=\"padDot\"></div></div>\n"
"  <div class=\"pad-labels\"><span>pitch ↑</span><span>brighter →</span></div>\n"
"</section>\n"
"\n"
"<section>\n"
"  <h2>Sound</h2>\n"
"  <div class=\"slider-row\"><label>Master volume</label><input type=\"range\" id=\"master\" min=\"0\" max=\"4\" step=\"0.05\"><span class=\"val\" id=\"masterV\"></span></div>\n"
"  <div class=\"slider-row\"><label>Home row softness</label><input type=\"range\" id=\"hrs\" min=\"0\" max=\"2\" step=\"0.05\"><span class=\"val\" id=\"hrsV\"></span></div>\n"
"  <div class=\"slider-row\"><label>Enter sound</label>\n"
"    <select id=\"enter\">\n"
"      <option value=\"\">— none —</option>\n"
"      <option value=\"typewriter-enter.mp3\">Typewriter</option>\n"
"      <option value=\"faahh-enter.mp3\">Faahh</option>\n"
"    </select>\n"
"  </div>\n"
"  <div class=\"slider-row\"><label>Enter volume</label><input type=\"range\" id=\"enterV\" min=\"0\" max=\"2\" step=\"0.05\"><span class=\"val\" id=\"enterVV\"></span></div>\n"
"  <div class=\"toggle\"><label>Spatial audio <span class=\"hint\">(pan by physical key position)</span></label><div class=\"sw\" data-k=\"spatial_audio\" id=\"t-spatial\"></div></div>\n"
"  <div class=\"toggle\"><label>Per-key feel <span class=\"hint\">(home row softer, stretch keys louder)</span></label><div class=\"sw\" data-k=\"per_key_feel\" id=\"t-feel\"></div></div>\n"
"  <div class=\"toggle\"><label>Volume normalization</label><div class=\"sw\" data-k=\"volume_normalization\" id=\"t-norm\"></div></div>\n"
"  <div class=\"toggle\"><label>Mute modifiers</label><div class=\"sw\" data-k=\"mute_modifiers\" id=\"t-mmod\"></div></div>\n"
"  <div class=\"toggle\"><label>Mouse click sounds</label><div class=\"sw\" data-k=\"mouse_clicks\" id=\"t-mouse\"></div></div>\n"
"  <div class=\"toggle\"><label>Hover preview</label><div class=\"sw\" data-k=\"hover_preview\" id=\"t-hover\"></div></div>\n"
"  <div class=\"toggle\"><label>Enabled</label><div class=\"sw\" data-k=\"enabled\" id=\"t-enabled\"></div></div>\n"
"</section>\n"
"\n"
"<section>\n"
"  <h2>Visualizer</h2>\n"
"  <div id=\"keys\"></div>\n"
"  <p class=\"hint\">Live key events from the daemon (SSE).</p>\n"
"</section>\n"
"\n"
"<script>\n"
"let S = {}; // settings cache\n"
"let profiles = [];\n"
"const $ = id => document.getElementById(id);\n"
"\n"
"async function api(path, method='GET', body) {\n"
"  const r = await fetch(path, {method, body});\n"
"  return r.json();\n"
"}\n"
"\n"
"/* ---------- keyboard visualizer ---------- */\n"
"const ROWS = [\n"
"  [[\"Esc\",1],[\"F1\",59],[\"F2\",60],[\"F3\",61],[\"F4\",62],[\"F5\",63],[\"F6\",64],[\"F7\",65],[\"F8\",66],[\"F9\",67],[\"F10\",68],[\"F11\",87],[\"F12\",88]],\n"
"  [[\"`\",41],[\"1\",2],[\"2\",3],[\"3\",4],[\"4\",5],[\"5\",6],[\"6\",7],[\"7\",8],[\"8\",9],[\"9\",10],[\"0\",11],[\"-\",12],[\"=\",13],[\"⌫\",14,\"w2\"]],\n"
"  [[\"Tab\",15,\"w2\"],[\"Q\",16],[\"W\",17],[\"E\",18],[\"R\",19],[\"T\",20],[\"Y\",21],[\"U\",22],[\"I\",23],[\"O\",24],[\"P\",25],[\"[\",26],[\"]\",27],[\"\\\\\",43]],\n"
"  [[\"Caps\",58,\"w2\"],[\"A\",30],[\"S\",31],[\"D\",32],[\"F\",33],[\"G\",34],[\"H\",35],[\"J\",36],[\"K\",37],[\"L\",38],[\";\",39],[\"'\",40],[\"↵\",28,\"w2\"]],\n"
"  [[\"Shift\",42,\"w2\"],[\"Z\",44],[\"X\",45],[\"C\",46],[\"V\",47],[\"B\",48],[\"N\",49],[\"M\",50],[\",\",51],[\".\",52],[\"/\",53],[\"Shift\",54,\"w2\"]],\n"
"  [[\"Ctrl\",29],[\"Win\",125],[\"Alt\",56],[\"Space\",57,\"w15\"],[\"Alt\",100],[\"Fn\",0],[\"☰\",127],[\"Ctrl\",97]],\n"
"  [[\"←\",105],[\"↑\",103],[\"↓\",108],[\"→\",106]],\n"
"];\n"
"function drawKb(){\n"
"  const el=$(\"keys\"); el.innerHTML=\"\";\n"
"  for(const row of ROWS){\n"
"    for(const [label,code,cls] of row){\n"
"      const d=document.createElement(\"div\");\n"
"      d.className=\"key\"+(cls?\" \"+cls:\"\");\n"
"      d.dataset.code=code; d.textContent=label;\n"
"      el.appendChild(d);\n"
"    }\n"
"  }\n"
"}\n"
"function lit(code,down){\n"
"  if(!down) return;\n"
"  const k=document.querySelector(`.key[data-code=\"${code}\"]`);\n"
"  if(!k) return;\n"
"  k.classList.add(\"lit\");\n"
"  setTimeout(()=>k.classList.remove(\"lit\"),140);\n"
"}\n"
"const es = new EventSource(\"/api/events\");\n"
"es.onmessage = e => { const j=JSON.parse(e.data); lit(j.code, j.phase===0); };\n"
"\n"
"/* ---------- switches ---------- */\n"
"function renderSwitches(){\n"
"  const byBrand={};\n"
"  for(const p of profiles){\n"
"    (byBrand[p.brand] ||= []).push(p);\n"
"  }\n"
"  const el=$(\"switches\"); el.innerHTML=\"\";\n"
"  for(const [brand,list] of Object.entries(byBrand)){\n"
"    const wrap=document.createElement(\"div\"); wrap.className=\"brand\";\n"
"    wrap.innerHTML=`<h3>${brand}</h3>`;\n"
"    const grid=document.createElement(\"div\"); grid.className=\"grid\";\n"
"    for(const p of list){\n"
"      const c=document.createElement(\"div\");\n"
"      c.className=\"card\"+(p.name===S.profile?\" active\":\"\");\n"
"      c.dataset.name=p.name;\n"
"      c.innerHTML=`<button class=\"star ${p.favorite?'on':''}\">★</button>\n"
"        <div class=\"row\"><span class=\"dot\" style=\"background:${p.color}\"></span><span class=\"name\">${p.display}</span></div>\n"
"        <div class=\"meta\">${p.type}</div>\n"
"        ${p.contributor?`<div class=\"by\">by ${p.contributor}</div>`:\"\"}`;\n"
"      c.onclick=async ev=>{\n"
"        if(ev.target.classList.contains(\"star\")) return;\n"
"        await api(\"/api/select?name=\"+encodeURIComponent(p.name),\"POST\");\n"
"        S.profile=p.name; renderSwitches(); $(\"cur\").textContent=p.display;\n"
"        await api(\"/api/preview?name=\"+encodeURIComponent(p.name)+\"&mode=burst\",\"POST\");\n"
"      };\n"
"      c.onmouseenter=async()=>{\n"
"        if(!S.hover_preview) return;\n"
"        await api(\"/api/preview?name=\"+encodeURIComponent(p.name)+\"&mode=hover\",\"POST\");\n"
"      };\n"
"      c.querySelector(\".star\").onclick=async ev=>{\n"
"        ev.stopPropagation();\n"
"        p.favorite=!p.favorite;\n"
"        await api(`/api/favorites?name=${encodeURIComponent(p.name)}&on=${p.favorite?1:0}`,\"POST\");\n"
"        renderSwitches();\n"
"      };\n"
"      grid.appendChild(c);\n"
"    }\n"
"    wrap.appendChild(grid); el.appendChild(wrap);\n"
"  }\n"
"}\n"
"\n"
"/* ---------- settings ---------- */\n"
"function bindSwitch(id,key){\n"
"  const el=$(id);\n"
"  el.onclick=async()=>{\n"
"    S[key]=!S[key];\n"
"    el.classList.toggle(\"on\",S[key]);\n"
"    await api(\"/api/settings\",\"POST\",JSON.stringify({[key]:S[key]}));\n"
"  };\n"
"  el.classList.toggle(\"on\",!!S[key]);\n"
"}\n"
"function bindSlider(id,valId,key,fmt){\n"
"  const el=$(id);\n"
"  el.oninput=async()=>{\n"
"    S[key]=parseFloat(el.value);\n"
"    $(valId).textContent=fmt?fmt(S[key]):S[key];\n"
"  };\n"
"  el.onchange=async()=>{ await api(\"/api/settings\",\"POST\",JSON.stringify({[key]:parseFloat(el.value)})); };\n"
"  el.value=S[key]; $(valId).textContent=fmt?fmt(S[key]):S[key];\n"
"}\n"
"\n"
"/* ---------- tone pad ---------- */\n"
"const pad=$(\"pad\");\n"
"let padDown=false;\n"
"function setPad(ev){\n"
"  const r=pad.getBoundingClientRect();\n"
"  const x=Math.min(Math.max((ev.clientX-r.left)/r.width,0),1);\n"
"  const y=Math.min(Math.max((ev.clientY-r.top)/r.height,0),1);\n"
"  S.tone_lpf=+x.toFixed(3); S.tone_pitch=+(0.88+0.24*y).toFixed(3);\n"
"  $(\"padDot\").style.left=(x*100)+\"%\"; $(\"padDot\").style.top=(y*100)+\"%\";\n"
"  api(\"/api/settings\",\"POST\",JSON.stringify({tone_lpf:S.tone_lpf,tone_pitch:S.tone_pitch}));\n"
"}\n"
"pad.addEventListener(\"pointerdown\",e=>{padDown=true;setPad(e);pad.setPointerCapture(e.pointerId)});\n"
"pad.addEventListener(\"pointermove\",e=>{if(padDown)setPad(e)});\n"
"pad.addEventListener(\"pointerup\",()=>padDown=false);\n"
"function placePad(){\n"
"  const x=S.tone_lpf??0.5, y=((S.tone_pitch??1)-0.88)/0.24;\n"
"  $(\"padDot\").style.left=(x*100)+\"%\"; $(\"padDot\").style.top=(y*100)+\"%\";\n"
"}\n"
"\n"
"/* ---------- init ---------- */\n"
"async function refresh(){\n"
"  profiles = (await api(\"/api/profiles\")).profiles;\n"
"  S = await api(\"/api/settings\");\n"
"  const st = await api(\"/api/status\");\n"
"  const cur = profiles.find(p=>p.name===S.profile);\n"
"  $(\"cur\").textContent = cur?cur.display:S.profile;\n"
"  $(\"engine\").textContent = st.muted?\"muted\":\"live\";\n"
"  $(\"muteBtn\").textContent = st.muted?\"Unmute\":\"Mute\";\n"
"  bindSwitch(\"t-spatial\",\"spatial_audio\");\n"
"  bindSwitch(\"t-feel\",\"per_key_feel\");\n"
"  bindSwitch(\"t-norm\",\"volume_normalization\");\n"
"  bindSwitch(\"t-mmod\",\"mute_modifiers\");\n"
"  bindSwitch(\"t-mouse\",\"mouse_clicks\");\n"
"  bindSwitch(\"t-hover\",\"hover_preview\");\n"
"  bindSwitch(\"t-enabled\",\"enabled\");\n"
"  bindSlider(\"master\",\"masterV\",\"master_volume\",v=>v.toFixed(2));\n"
"  bindSlider(\"hrs\",\"hrsV\",\"home_row_softness\",v=>v.toFixed(2));\n"
"  bindSlider(\"enterV\",\"enterVV\",\"enter_volume\",v=>v.toFixed(2));\n"
"  $(\"enter\").value=S.enter_sound||\"\";\n"
"  $(\"enter\").onchange=async()=>{ S.enter_sound=$(\"enter\").value; await api(\"/api/settings\",\"POST\",JSON.stringify({enter_sound:S.enter_sound})); };\n"
"  placePad();\n"
"  renderSwitches();\n"
"}\n"
"$(\"muteBtn\").onclick=async()=>{ await api(\"/api/toggle-mute\",\"POST\"); refresh(); };\n"
"drawKb(); refresh();\n"
"</script>\n"
"</body>\n"
"</html>\n"
"\n"
;
